### ISSUE TITLE
After b8efb2e, registerSimpleDataParagraph pass empty string

### ISSUE THREAD

**Issue by Omochice** [tani/podium#5]
# Summary

After b8efb2e708ea45a47df65d48c44d2ee3b7888b89, `registerSimpleDataParagraph` pass empty string to registered functions.

## Environment

- OS: Ubuntu20.04.6 LTS(via WSL2 on Windows10)
- Lua: `Lua 5.4.6  Copyright (C) 1994-2023 Lua.org, PUC-Rio`

## Reproduce

Place `sample.lua` to project root (same layer with `README.pod`):

```lua
local podium = require("lua/podium")

local backend = podium.markdown

local inputString = [[
=pod

=begin sample

hi

=end sample

=cut
]]

backend:registerSimpleDataParagraph(
  "sample",
  function(text)
    return "```sample\n"  .. text .. "\n```"
  end
)

print(podium.process(backend, inputString))
```

and place `sample.pod` too.

```pod
=pod

=begin sample

hi

=end sample

=cut
```

## Expect behavior

Output below:

````console

```sample
hi
```

````

## Actual behavior

Output below:

````console
```sample

```
````

## Note

If change `registerSimpleDataParagraph` below, we can fix this problem.

But looks better to fix `findDataParagraph`.

```diff
- local _, startIndex, endIndex, _ = findDataParagraph(element)
+ local startIndex, _, endIndex, _ = findDataParagraph(element)
```

If above is no problem, I will create PR.

**Comment by tani** [comment]
Thank you for reporting issue!
I have solved this problem just now. Please check it!
Cheers!

**Comment by Omochice** [comment]
I checked it work well.
Thank you for great work! 👍🏻
